'use strict';
const crypto=require('crypto');
const digest=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
function createContactStore(pool){let ready=false;
 const need=()=>{if(!ready||!pool)throw Error('verification_store_unavailable')};
 async function transaction(fn){need();const c=await pool.connect();try{await c.query('begin');const v=await fn(c);await c.query('commit');return v}catch(e){try{await c.query('rollback')}catch{}throw e}finally{c.release()}}
 return{
  ready:()=>ready,
  async init(){if(!pool)return;await pool.query(`create table if not exists contact_verification_limits(key_hash text primary key,window_start timestamptz not null default now(),attempts integer not null default 0)`);await pool.query(`create table if not exists contact_verifications(token_hash text primary key,user_id uuid not null references users(id) on delete cascade,channel text not null check(channel in ('sms','email')),destination_hash text not null,provider_sid text,state text not null default 'creating',attempts integer not null default 0,created_at timestamptz not null default now(),expires_at timestamptz not null default now()+interval '10 minutes')`);await pool.query('create index if not exists idx_contact_limit_window on contact_verification_limits(window_start)');await pool.query('create index if not exists idx_contact_verification_expiry on contact_verifications(expires_at)');ready=true},
  async rate(key,maximum,seconds){need();const r=await pool.query(`insert into contact_verification_limits(key_hash,attempts) values($1,1) on conflict(key_hash) do update set attempts=case when contact_verification_limits.window_start<=now()-($2::int*interval '1 second') then 1 else least(contact_verification_limits.attempts+1,$3::int+1) end,window_start=case when contact_verification_limits.window_start<=now()-($2::int*interval '1 second') then now() else contact_verification_limits.window_start end returning attempts`,[digest(key),seconds,maximum]);if(key.endsWith(':global'))await pool.query("delete from contact_verification_limits where window_start<now()-interval '1 day'");return r.rows[0]?.attempts<=maximum},
  async create(user,channel,to,tokenHash){return transaction(async c=>{await c.query('select pg_advisory_xact_lock(hashtext($1))',['verify:'+user.id+':'+channel]);const recent=await c.query(`select 1 from contact_verifications where user_id=$1 and channel=$2 and created_at>now()-interval '60 seconds' limit 1`,[user.id,channel]);if(recent.rows.length)return false;await c.query('insert into contact_verifications(token_hash,user_id,channel,destination_hash) values($1,$2,$3,$4)',[tokenHash,user.id,channel,digest(to)]);await c.query(`delete from contact_verifications where expires_at<now()-interval '1 day'`);await c.query(`delete from contact_verification_limits where window_start<now()-interval '1 day'`);return true})},
  async issue(tokenHash,sid){need();const r=await pool.query(`update contact_verifications set provider_sid=$2,state='issued' where token_hash=$1 and state='creating' and expires_at>now() returning token_hash`,[tokenHash,sid]);return r.rows.length===1},
  async expire(tokenHash){need();await pool.query(`update contact_verifications set state='expired' where token_hash=$1 and state<>'consumed'`,[tokenHash])},
  async claim(tokenHash){return transaction(async c=>{const r=await c.query(`update contact_verifications set state='checking',attempts=attempts+1 where token_hash=$1 and state='issued' and attempts<5 and expires_at>now() returning *`,[tokenHash]);if(!r.rows[0])return null;const challenge=r.rows[0],u=await c.query('select id,email,phone,member_status,email_verified,phone_verified from users where id=$1',[challenge.user_id]);const user=u.rows[0];if(!user||user.member_status!=='pending_verification'||digest(challenge.channel==='sms'?user.phone:user.email)!==challenge.destination_hash){await c.query(`update contact_verifications set state='expired' where token_hash=$1`,[tokenHash]);return null}return{challenge,user}})},
  async release(tokenHash){need();await pool.query(`update contact_verifications set state=case when attempts>=5 then 'expired' else 'issued' end where token_hash=$1 and state='checking'`,[tokenHash])},
  async approve(tokenHash){return transaction(async c=>{const r=await c.query(`select * from contact_verifications where token_hash=$1 and state='checking' and expires_at>now() for update`,[tokenHash]);const challenge=r.rows[0];if(!challenge)return null;const u=await c.query('select id,email,phone,member_status from users where id=$1 for update',[challenge.user_id]);const user=u.rows[0];if(!user||user.member_status!=='pending_verification'||digest(challenge.channel==='sms'?user.phone:user.email)!==challenge.destination_hash){await c.query(`update contact_verifications set state='expired' where token_hash=$1`,[tokenHash]);return null}
   const field=challenge.channel==='sms'?'phone_verified':'email_verified',other=challenge.channel==='sms'?'email_verified':'phone_verified';const updated=await c.query(`update users set ${field}=true,member_status=case when ${other}=true then 'active' else member_status end where id=$1 and member_status='pending_verification' returning email_verified,phone_verified,member_status`,[user.id]);if(!updated.rows[0])return null;await c.query(`update contact_verifications set state='consumed' where token_hash=$1`,[tokenHash]);return updated.rows[0]})}
 };
}
module.exports={createContactStore,digest};
