const test=require('node:test'),assert=require('node:assert/strict');const {createContactStore,digest}=require('./contact-store');
function setup(){const calls=[],rows=new Map();let released=0,fail=false;const user={id:'TEST',email:'one@example.test',phone:'+15550100101',member_status:'pending_verification',email_verified:false,phone_verified:false};const client={async query(sql,values=[]){calls.push({sql,values});if(fail&&sql.startsWith('update users'))throw Error('simulated write failure');if(sql.startsWith('select 1 from contact_verifications'))return{rows:[]};if(sql.startsWith('insert into contact_verification_limits'))return{rows:[{attempts:1}]};if(sql.startsWith('update contact_verifications set provider_sid'))return{rows:[{token_hash:'hash'}]};if(sql.startsWith('insert into contact_verifications')){rows.set(values[0],{token_hash:values[0],user_id:values[1],channel:values[2],destination_hash:values[3],state:'creating',attempts:0});return{rows:[]}}if(sql.startsWith("update contact_verifications set state='checking'")){const c=rows.get(values[0]);if(!c)return{rows:[]};return{rows:[c]}}if(sql.startsWith('select * from contact_verifications'))return{rows:rows.has(values[0])?[rows.get(values[0])]:[]};if(sql.startsWith('select id,email,phone'))return{rows:[user]};if(sql.startsWith('update users')){if(sql.startsWith('update users set phone_verified=true'))user.phone_verified=true;else user.email_verified=true;if(user.phone_verified&&user.email_verified)user.member_status='active';return{rows:[{...user}]}}return{rows:[]}},release(){released++}};const pool={query:client.query,connect:async()=>client};const store=createContactStore(pool);return{store,calls,user,rows,setFailure(){fail=true},get released(){return released}}}
test('missing database readiness false and mutations blocked',async()=>{const s=createContactStore(null);await s.init();assert.equal(s.ready(),false);await assert.rejects(s.rate('x',1,1));await assert.rejects(s.claim('hash'))});
test('additive schema contains no OTP, password or raw contact columns',async()=>{const s=setup();await s.store.init();assert.equal(s.store.ready(),true);const tables=s.calls.filter(c=>c.sql.startsWith('create table')).map(c=>c.sql).join(' ');assert.ok(tables.includes('destination_hash'));assert.ok(!tables.includes('password'));assert.ok(!tables.includes('otp'));assert.ok(!tables.includes('phone text'));assert.ok(!tables.includes('email text'))});
test('rate limit is durable atomic upsert with bounded attempts and valid typed parameters',async()=>{const s=setup();await s.store.init();assert.equal(await s.store.rate('credential:one@example.test',10,900),true);const c=s.calls.find(c=>c.sql.startsWith('insert into contact_verification_limits'));assert.deepEqual(c.values,[digest('credential:one@example.test'),900,10]);assert.ok(c.sql.includes('on conflict'));assert.ok(c.sql.includes('least('));assert.ok(!c.sql.includes('one@example.test'))});
test('global rate calls prune expired keys',async()=>{const s=setup();await s.store.init();await s.store.rate('credential:global',100,900);assert.ok(s.calls.some(c=>c.sql.startsWith('delete from contact_verification_limits')))});
test('challenge creation locks user/channel and stores only hashed binding',async()=>{const s=setup();await s.store.init();await s.store.create(s.user,'sms',s.user.phone,'HASH');const q=s.calls.find(c=>c.sql.startsWith('insert into contact_verifications'));assert.deepEqual(q.values,['HASH','TEST','sms',digest(s.user.phone)]);assert.ok(s.calls.some(c=>c.sql.includes('pg_advisory_xact_lock')));assert.ok(s.calls.some(c=>c.sql==='commit'));assert.equal(s.released,1)});
test('claim atomically enforces issued state expiry five-attempt limit',async()=>{const s=setup();await s.store.init();await s.store.create(s.user,'sms',s.user.phone,'HASH');await s.store.claim('HASH');const q=s.calls.find(c=>c.sql.startsWith("update contact_verifications set state='checking'"));assert.ok(q.sql.includes("state='issued'"));assert.ok(q.sql.includes('attempts<5'));assert.ok(q.sql.includes('expires_at>now()'))});
test('claim rejects contact mismatch and blocks approval',async()=>{const s=setup();await s.store.init();await s.store.create(s.user,'sms',s.user.phone,'HASH');s.user.phone='+15550100999';assert.equal(await s.store.claim('HASH'),null);assert.ok(s.calls.some(c=>c.sql.startsWith("update contact_verifications set state='expired'")))});
test('claim rejects blocked account',async()=>{const s=setup();await s.store.init();await s.store.create(s.user,'sms',s.user.phone,'HASH');s.user.member_status='blocked';assert.equal(await s.store.claim('HASH'),null)});
test('approval locks challenge and user; flags and consumption commit atomically',async()=>{const s=setup();await s.store.init();await s.store.create(s.user,'sms',s.user.phone,'HASH');const r=await s.store.approve('HASH');assert.equal(r.phone_verified,true);assert.equal(r.member_status,'pending_verification');assert.ok(s.calls.some(c=>c.sql.startsWith('select * from contact_verifications')&&c.sql.includes('for update')));assert.ok(s.calls.some(c=>c.sql.startsWith('select id,email,phone')&&c.sql.includes('for update')));assert.ok(s.calls.some(c=>c.sql.includes("state='consumed'")))});
test('email plus phone approval activates exact pending user',async()=>{const s=setup();await s.store.init();s.user.phone_verified=true;await s.store.create(s.user,'email',s.user.email,'HASH');const r=await s.store.approve('HASH');assert.equal(r.member_status,'active');const q=s.calls.find(c=>c.sql.startsWith('update users'));assert.deepEqual(q.values,['TEST']);assert.ok(q.sql.includes("member_status='pending_verification'"));assert.ok(q.sql.includes("when phone_verified=true then 'active'"))});
test('approval rechecks destination under lock',async()=>{const s=setup();await s.store.init();await s.store.create(s.user,'email',s.user.email,'HASH');s.user.email='changed@example.test';assert.equal(await s.store.approve('HASH'),null);assert.equal(s.user.email_verified,false)});
test('approval write failure rolls back and releases DB client',async()=>{const s=setup();await s.store.init();await s.store.create(s.user,'sms',s.user.phone,'HASH');s.setFailure();await assert.rejects(s.store.approve('HASH'));assert.ok(s.calls.some(c=>c.sql==='rollback'));assert.equal(s.released,2);assert.equal(s.user.phone_verified,false)});
test('release keeps attempt bound; consumed state cannot be expired again',async()=>{const s=setup();await s.store.init();await s.store.release('HASH');await s.store.expire('HASH');assert.ok(s.calls.some(c=>c.sql.includes('when attempts>=5')));assert.ok(s.calls.some(c=>c.sql.includes("state<>'consumed'")))});
