const test=require('node:test'),assert=require('node:assert/strict');const {createContactProvider}=require('./contact-provider');
const env={TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_API_KEY:'SK'+'b'.repeat(32),TWILIO_API_SECRET:'PRIVATE-SECRET-'.repeat(3),TWILIO_VERIFY_SERVICE_SID:'VA'+'c'.repeat(32),TWILIO_VERIFY_SMS_ENABLED:'true',TWILIO_VERIFY_EMAIL_ENABLED:'true'};const sid='VE'+'d'.repeat(32),to='+15550100101';
const response=(changes={})=>({sid,to,channel:'sms',status:'pending',account_sid:env.TWILIO_ACCOUNT_SID,service_sid:env.TWILIO_VERIFY_SERVICE_SID,...changes});
function setup(data=response(),status=200){const calls=[];const provider=createContactProvider({env,fetchImpl:async(url,options)=>{calls.push({url,options});return{ok:status>=200&&status<300,status,json:async()=>data}}});return{provider,calls}}
test('default disabled means no outbound requests',async()=>{let calls=0;const p=createContactProvider({env:{},fetchImpl:async()=>{calls++}});assert.equal(p.readiness().configured,false);await assert.rejects(p.start('sms',to),{code:'verification_not_connected'});assert.equal(calls,0)});
test('both channels have explicit independent enable flags',()=>{for(const channel of ['sms','email']){const p=createContactProvider({env:{...env,[channel==='sms'?'TWILIO_VERIFY_SMS_ENABLED':'TWILIO_VERIFY_EMAIL_ENABLED']:'false'}});assert.equal(p.readiness().channels[channel],false)}});
test('configured credentials alone do not enable delivery',()=>{assert.deepEqual(createContactProvider({env:{...env,TWILIO_VERIFY_SMS_ENABLED:'',TWILIO_VERIFY_EMAIL_ENABLED:''}}).readiness().channels,{sms:false,email:false})});
test('status omits all credential values and SIDs',()=>{const r=JSON.stringify(createContactProvider({env}).readiness());for(const k of ['TWILIO_ACCOUNT_SID','TWILIO_API_KEY','TWILIO_API_SECRET','TWILIO_VERIFY_SERVICE_SID'])assert.ok(!r.includes(env[k]))});
test('valid start uses fixed endpoint and private Basic authorization',async()=>{const {provider,calls}=setup();assert.deepEqual(await provider.start('sms',to),{sid});assert.equal(calls[0].url,'https://verify.twilio.com/v2/Services/'+env.TWILIO_VERIFY_SERVICE_SID+'/Verifications');assert.equal(calls[0].options.redirect,'error');assert.equal(calls[0].options.headers.Authorization,'Basic '+Buffer.from(env.TWILIO_API_KEY+':'+env.TWILIO_API_SECRET).toString('base64'));assert.deepEqual(Object.fromEntries(new URLSearchParams(calls[0].options.body)),{To:to,Channel:'sms'})});
for(const [name,destination]of [['invalid','1555'],['foreign country','+445550100101'],['URL injection','https://evil.test'],['oversized','+'+'1'.repeat(20)]])test(name+' phone rejected before sending',async()=>{const {provider,calls}=setup();await assert.rejects(provider.start('sms',destination));assert.equal(calls.length,0)});
test('email start sends only the registered email',async()=>{const {provider,calls}=setup(response({to:'person@example.test',channel:'email'}));await provider.start('email','person@example.test');assert.deepEqual(Object.fromEntries(new URLSearchParams(calls[0].options.body)),{To:'person@example.test',Channel:'email'})});
for(const [name,changes]of [['service mismatch',{service_sid:'VA'+'e'.repeat(32)}],['account mismatch',{account_sid:'AC'+'e'.repeat(32)}],['destination mismatch',{to:'+15550100999'}],['channel mismatch',{channel:'email'}],['invalid SID',{sid:'hostile'}],['already approved start',{status:'approved'}]])test('start rejects '+name,async()=>{const {provider}=setup(response(changes));await assert.rejects(provider.start('sms',to),{code:'verification_provider_unavailable'})});
test('approved status validates exact challenge binding',async()=>{const {provider,calls}=setup(response({status:'approved'}));assert.deepEqual(await provider.check('sms',to,sid,'123456'),{approved:true});assert.deepEqual(Object.fromEntries(new URLSearchParams(calls[0].options.body)),{VerificationSid:sid,Code:'123456'});assert.ok(!calls[0].url.includes('123456'))});
test('legacy valid=true without approved status cannot verify',async()=>{const {provider}=setup(response({valid:true}));assert.deepEqual(await provider.check('sms',to,sid,'123456'),{approved:false})});
test('foreign challenge SID cannot verify',async()=>{const {provider}=setup(response({status:'approved',sid:'VE'+'e'.repeat(32)}));await assert.rejects(provider.check('sms',to,sid,'123456'),{code:'verification_provider_unavailable'})});
for(const code of ['1','12345678901','<script>','abc123','12 34'])test('invalid code format '+code+' rejected before network',async()=>{const {provider,calls}=setup();await assert.rejects(provider.check('sms',to,sid,code),{code:'invalid_verification_input'});assert.equal(calls.length,0)});
for(const [status,code]of [[401,'verification_provider_unavailable'],[403,'verification_provider_unavailable'],[429,'verification_rate_limited'],[500,'verification_provider_unavailable'],[404,'verification_expired']])test('safe provider status '+status,async()=>{const {provider}=setup({message:env.TWILIO_API_SECRET},status);await assert.rejects(provider.check('sms',to,sid,'123456'),error=>error.code===code&&!String(error).includes(env.TWILIO_API_SECRET))});
test('network and malformed JSON errors never leak provider data',async()=>{for(const fetchImpl of [async()=>{throw Error(env.TWILIO_API_SECRET)},async()=>({ok:true,json:async()=>{throw Error('123456 '+env.TWILIO_API_SECRET)}})])await assert.rejects(createContactProvider({env,fetchImpl}).start('sms',to),error=>error.code==='verification_provider_unavailable'&&!String(error).includes(env.TWILIO_API_SECRET))});
test('empty/invalid prefix configuration cannot permit foreign numbers',async()=>{const p=createContactProvider({env:{...env,VERIFY_SMS_PREFIXES:'*'},fetchImpl:async()=>{throw Error('must not call')}});await assert.rejects(p.start('sms',to),{code:'phone_country_not_enabled'})});
