const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Readable}=require('node:stream');
const {createProviderAuth,safeOrigin}=require('./provider-auth');
const env={OAUTH_PROVIDER_PROOF_ENABLED:'true',GOOGLE_CLIENT_ID:'test-google',GOOGLE_CLIENT_SECRET:'test-google-secret',MICROSOFT_CLIENT_ID:'test-ms',MICROSOFT_CLIENT_SECRET:'test-ms-secret',APPLE_SERVICES_ID:'test-apple',APPLE_CLIENT_SECRET:'test-apple-secret'};
function fixture(extra={}){
 const calls=[];let fail=false,claims={sub:'TEST subject',iss:'https://accounts.google.com'};
 const oidc={discovery:async(url,id,secret)=>{calls.push({kind:'discovery',url:url.href,id,secret});return {id}},enableNonRepudiationChecks:c=>calls.push({kind:'signature',id:c.id}),randomPKCECodeVerifier:()=>('TEST-verifier-'.repeat(5)),calculatePKCECodeChallenge:async()=> 'TEST-S256',buildAuthorizationUrl:(c,p)=>{calls.push({kind:'authorize',p});const u=new URL('https://provider.example/authorize');for(const[k,v]of Object.entries(p))u.searchParams.set(k,v);return u},authorizationCodeGrant:async(c,r,checks)=>{calls.push({kind:'grant',c,r,checks});if(fail)throw Error('invalid ID token');return {claims:()=>claims}}};
 let clock=1000;const auth=createProviderAuth({env:{...env,...extra},loadOIDC:async()=>oidc,now:()=>clock,...(extra.maxFlows?{maxFlows:extra.maxFlows}:{})});
 async function request(url,method='GET',headers={},body=''){const req=Readable.from(body?[body]:[]);Object.assign(req,{url,method,headers});const res={status:0,headers:{},body:'',writeHead(s,h){this.status=s;this.headers=h},end(b=''){this.body=b}};const matched=await auth.handle(req,res,(r,s,d,h={})=>{r.writeHead(s,h);r.end(JSON.stringify(d))});return {...res,matched,json:()=>JSON.parse(res.body)}}
 async function start(id='google'){const r=await request('/api/auth/provider/'+id+'/start');return {r,state:new URL(r.headers.location).searchParams.get('state'),cookie:r.headers['set-cookie'].split(';')[0],id}}
 function callback(s,params={},method='GET',headers={}){const p=new URLSearchParams({state:s.state,code:'TEST-code',...params});return request('/api/auth/provider/'+s.id+'/callback'+(method==='GET'?'?'+p:''),method,{cookie:s.cookie,...headers,...(method==='POST'?{'content-type':'application/x-www-form-urlencoded'}:{})},method==='POST'?p.toString():'')}
 return {auth,request,start,callback,calls,setClock:v=>clock=v,setFail:v=>fail=v,setClaims:v=>claims=v};
}
test('library exports match installed integration API',async()=>{const m=await import('openid-client');for(const k of ['discovery','authorizationCodeGrant','enableNonRepudiationChecks'])assert.equal(typeof m[k],'function')});
test('HTTPS origins reject paths, credentials and external return parameters',()=>{assert.equal(safeOrigin('https://safe.example'),'https://safe.example');for(const v of ['http://safe.example','https://x:y@safe.example','https://safe.example/path','https://safe.example/?next=evil'])assert.equal(safeOrigin(v),null)});
test('default disabled routes expose no credential values',async()=>{const f=fixture({OAUTH_PROVIDER_PROOF_ENABLED:undefined});const r=await f.request('/api/auth/providers');assert.equal(r.status,200);assert.equal(r.json().membershipSignupConnected,false);assert.equal(r.json().phoneVerificationRequired,true);assert.ok(r.json().providers.every(p=>!p.available));assert.ok(!r.body.includes('test-google-secret'));assert.equal((await f.request('/api/auth/provider/google/start')).status,503);assert.equal(f.calls.length,0)});
test('missing credentials fail closed',async()=>{const f=fixture({APPLE_CLIENT_SECRET:''});assert.equal((await f.request('/api/auth/provider/apple/start')).status,503)});
test('unknown routes and unsupported methods reject',async()=>{const f=fixture();assert.equal((await f.request('/api/auth/provider/__proto__/start')).status,404);assert.equal((await f.request('/api/auth/providers','POST')).status,405);assert.equal((await f.request('/api/auth/provider/google/start','POST')).status,405)});
test('start uses code, nonce, state, S256 and secure browser cookie',async()=>{const f=fixture(),s=await f.start();assert.equal(s.r.status,302);const p=f.calls.find(c=>c.kind==='authorize').p;assert.equal(p.response_type,'code');assert.equal(p.scope,'openid email');assert.equal(p.code_challenge_method,'S256');assert.match(p.state,/^[A-Za-z0-9_-]{43}$/);assert.match(p.nonce,/^[A-Za-z0-9_-]{43}$/);assert.match(s.r.headers['set-cookie'],/HttpOnly; Secure; SameSite=None/);assert.ok(f.calls.some(c=>c.kind==='signature'))});
test('Google callback supplies validation checks and never emits identity/tokens',async()=>{const f=fixture(),s=await f.start(),r=await f.callback(s);assert.equal(r.status,303);assert.ok(r.headers.location.endsWith('provider_result=verification_pending&provider=google#cloudAccount'));const g=f.calls.find(c=>c.kind==='grant');assert.equal(g.checks.expectedState,s.state);assert.equal(g.checks.expectedNonce,f.calls.find(c=>c.kind==='authorize').p.nonce);assert.equal(g.checks.idTokenExpected,true);assert.ok(g.checks.pkceCodeVerifier);assert.ok(!JSON.stringify(r).includes('TEST subject'));assert.match(r.headers['set-cookie'],/Max-Age=0/)});
test('callback replay rejects before second token exchange',async()=>{const f=fixture(),s=await f.start();await f.callback(s);assert.equal((await f.callback(s)).status,400);assert.equal(f.calls.filter(c=>c.kind==='grant').length,1)});
test('wrong or missing browser binding rejects without consuming valid flow',async()=>{const f=fixture(),s=await f.start();let r=await f.callback(s,{},'GET',{cookie:''});assert.equal(r.status,400);assert.equal(r.headers['set-cookie'],undefined);assert.equal((await f.callback(s)).status,303)});
test('wrong state and duplicate state reject',async()=>{const f=fixture(),s=await f.start();assert.equal((await f.callback(s,{state:'x'.repeat(43)})).status,400);assert.equal((await f.request('/api/auth/provider/google/callback?state='+s.state+'&state='+s.state+'&code=x','GET',{cookie:s.cookie})).status,400);assert.equal((await f.callback(s)).status,303)});
test('expired state rejects',async()=>{const f=fixture(),s=await f.start();f.setClock(601001);assert.equal((await f.callback(s)).status,400);assert.equal(f.calls.filter(c=>c.kind==='grant').length,0)});
test('provider mix-up rejects',async()=>{const f=fixture(),s=await f.start();assert.equal((await f.request('/api/auth/provider/apple/callback?state='+s.state+'&code=x','GET',{cookie:s.cookie.replace('google','apple')})).status,400);assert.equal(f.calls.filter(c=>c.kind==='grant').length,0)});
test('cancellation consumes state without token exchange',async()=>{const f=fixture(),s=await f.start(),r=await f.callback(s,{error:'access_denied'});assert.equal(r.status,303);assert.ok(r.headers.location.includes('provider_result=cancelled'));assert.equal(f.calls.filter(c=>c.kind==='grant').length,0);assert.equal((await f.callback(s)).status,400)});
test('token validation rejection consumes state and creates no session',async()=>{const f=fixture(),s=await f.start();f.setFail(true);const r=await f.callback(s);assert.equal(r.status,400);assert.equal(r.json().membershipActivated,false);assert.equal((await f.callback(s)).status,400)});
test('missing identity claims reject',async()=>{const f=fixture(),s=await f.start();f.setClaims({});assert.equal((await f.callback(s)).status,400)});
test('Apple form_post passes a Request and fixed callback URI',async()=>{const f=fixture(),s=await f.start('apple');assert.equal(f.calls.find(c=>c.kind==='authorize').p.response_mode,'form_post');const r=await f.callback(s,{},'POST');assert.equal(r.status,303);const g=f.calls.find(c=>c.kind==='grant');assert.ok(g.r instanceof Request);assert.equal(g.r.method,'POST');assert.equal(g.r.url,'https://asharf-ul-makhlook-api.onrender.com/api/auth/provider/apple/callback')});
test('Microsoft uses the personal-account discovery endpoint',async()=>{const f=fixture();await f.start('microsoft');assert.equal(f.calls.find(c=>c.kind==='discovery').url,'https://login.microsoftonline.com/consumers/v2.0/.well-known/openid-configuration')});
test('bounded state capacity also holds under concurrent starts',async()=>{const f=fixture({maxFlows:1});const rs=await Promise.all([f.request('/api/auth/provider/google/start'),f.request('/api/auth/provider/apple/start')]);assert.deepEqual(rs.map(r=>r.status).sort(),[302,429])});
test('non-form callback and oversized form reject',async()=>{const f=fixture();assert.equal((await f.request('/api/auth/provider/apple/callback','POST',{'content-type':'application/json'},'{}')).status,400);assert.equal((await f.request('/api/auth/provider/apple/callback','POST',{'content-type':'application/x-www-form-urlencoded'},'x'.repeat(65537))).status,400)});
