const {test}=require('node:test');const assert=require('node:assert/strict');const {createPostgresFlowStore}=require('./provider-flow-store');
function database({total=0,failInsert=false}={}){const calls=[];let released=false;const db={async query(sql,values){calls.push({sql,values});if(sql.startsWith('select count'))return {rows:[{total}]};if(sql.startsWith('insert')&&failInsert)throw Error('TEST insert failure');return {rows:[]}},async connect(){return {...db,release(){released=true}}}};return {db,calls,get released(){return released}}}
const flow={id:'google',browser:'TEST hashed browser',nonce:'TEST nonce',verifier:'TEST verifier',expires:601000};
test('Postgres initialization creates independent table/index and expires old flows',async()=>{const f=database();await createPostgresFlowStore(f.db).init();assert.match(f.calls[0].sql,/create table if not exists provider_flows/);assert.match(f.calls[1].sql,/idx_provider_flows_expiry/);assert.match(f.calls[2].sql,/expires_at<=now/);assert.equal(f.calls.length,3)});
test('store readiness fails closed on missing database or failed schema probe',async()=>{assert.equal(await createPostgresFlowStore(null).ready(),false);assert.equal(await createPostgresFlowStore({query:async()=>{throw Error('TEST')}}).ready(),false)});
test('bounded insert locks shared capacity inside transaction and stores serializable fields only',async()=>{const f=database();assert.equal(await createPostgresFlowStore(f.db).create('TEST hashed state',flow,400,1000),true);assert.deepEqual(f.calls.map(x=>x.sql.split(' ')[0]),['BEGIN','select','delete','select','insert','COMMIT']);assert.match(f.calls[1].sql,/pg_advisory_xact_lock/);assert.deepEqual(f.calls[4].values,['TEST hashed state',flow.id,flow.browser,flow.nonce,flow.verifier,flow.expires]);assert.equal(f.released,true)});
test('capacity limit commits cleanup without inserting or leaking client',async()=>{const f=database({total:400});assert.equal(await createPostgresFlowStore(f.db).create('TEST',flow,400,1000),false);assert.equal(f.calls.some(x=>x.sql.startsWith('insert')),false);assert.equal(f.calls.at(-1).sql,'COMMIT');assert.equal(f.released,true)});
test('insert failure rolls back and releases client',async()=>{const f=database({failInsert:true});await assert.rejects(createPostgresFlowStore(f.db).create('TEST',flow,400,1000));assert.equal(f.calls.at(-1).sql,'ROLLBACK');assert.equal(f.released,true)});
test('consumption is one conditional atomic delete with returning and bound parameters',async()=>{const f=database();assert.equal(await createPostgresFlowStore(f.db).consume('TEST state','google','TEST browser',1000),null);assert.equal(f.calls.length,1);assert.match(f.calls[0].sql,/delete from provider_flows where state_hash=\$1 and provider=\$2 and browser_hash=\$3 and expires_at>.*returning/);assert.deepEqual(f.calls[0].values,['TEST state','google','TEST browser',1000])});
